name: "run-gradle"
description: "Run a Gradle Command"
author: "jzheaux"

inputs:
  gradle-args:
    description: "Gradle arguments"
    required: true

runs:
  using: "composite"
  steps:
    - name: Add init.gradle
      shell: bash
      run: |
        mkdir -p "$HOME/.gradle/init.d"
        cp "$GITHUB_ACTION_PATH/init.gradle" "$HOME/.gradle/init.d/init.gradle"
    - name: Run with Gradle
      shell: bash
      env:
        GRADLE_ARGS: ${{ inputs.gradle-args }}
      run: |
        ./gradlew $GRADLE_ARGS
