allprojects {
	repositories {
		if (project.hasProperty("artifactoryUsername") && project.hasProperty("artifactoryPassword")
				&& project.artifactoryUsername && project.artifactoryPassword) {
			maven {
				name "spring-commercial-release"
				url "https://repo.spring.io/artifactory/spring-commercial-release-remote"
				credentials {
					username project.artifactoryUsername
					password project.artifactoryPassword
				}
			}
		}
	}
}
