name: "pr-build"
description: "Build a pull request"
author: "jzheaux"

inputs:
  java-version:
    description: "The Java version to use"
    required: false
    default: "17"

runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: spring-io/spring-gradle-build-action@c8668747d7c264864c8c7f7026d0d277d14a78dc  # v2.0.6
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "temurin"

    - name: Build with Gradle
      shell: bash
      run: |
        ./gradlew clean build -PskipCheckExpectedBranchVersion=true --continue
