name: Perform Release
description: Idempotently performs Spring Security release announcement steps; to be performed after artifacts have been deployed

inputs:
  version:
    description: "The artifact version deployed"
    required: true
  website-token:
    description: "GitHub token with permissions to update the spring.io website"
    required: true
  gchat-webhook-url:
    description: "The GChat webhook URL to announce the release in the Spring Team GChat room"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - id: next-snapshot-version
      name: Calculate Next Snapshot Version
      uses: spring-io/spring-release-actions/compute-next-snapshot@708379dd0580adcd6dddf4e3754c8accec4801d4  # 0.0.3
      with:
        version: ${{ inputs.version }}
    - id: next-release-milestone
      name: Get Next Release Milestone
      uses: spring-io/spring-release-actions/compute-next-version@708379dd0580adcd6dddf4e3754c8accec4801d4  # 0.0.3
      with:
        version: ${{ inputs.version }}
        website-token: ${{ inputs.website-token }}
    - name: Generate Release Notes
      uses: spring-io/github-changelog-generator@c247eb874a8bbc2c7b91ed7227d8eb66eb639d38  # v0.0.13
      with:
        milestone: ${{ inputs.version }}
        token: ${{ github.token }}
        config-file: etc/release-notes-sections.yml
    - name: Create GitHub Release
      uses: spring-io/spring-release-actions/publish-release-notes@708379dd0580adcd6dddf4e3754c8accec4801d4  # 0.0.3
      with:
        tag: ${{ inputs.version }}
    - name: Close Milestone
      uses: spring-io/spring-release-actions/close-milestone@708379dd0580adcd6dddf4e3754c8accec4801d4  # 0.0.3
      with:
        version: ${{ inputs.version }}
    - name: Update Learn Page
      uses: spring-io/spring-release-actions/update-learn-page@708379dd0580adcd6dddf4e3754c8accec4801d4  # 0.0.3
      with:
        version: ${{ inputs.version }}
        website-token: ${{ inputs.website-token }}
        is-antora: true
    - name: Schedule Next Release (if not already scheduled)
      if: ${{ steps.next-release-milestone.outputs.version-type == 'oss' }}
      uses: spring-io/spring-release-actions/schedule-milestone@708379dd0580adcd6dddf4e3754c8accec4801d4  # 0.0.3
      with:
        version: ${{ steps.next-release-milestone.outputs.version }}
        version-date: ${{ steps.next-release-milestone.outputs.version-date }}
    - name: Announce Release on GChat
      uses: spring-io/spring-release-actions/announce-on-gchat@708379dd0580adcd6dddf4e3754c8accec4801d4  # 0.0.3
      with:
        version: ${{ inputs.version }}
        gchat-webhook-url: ${{ inputs.gchat-webhook-url }}
